#link https://symfony.com/doc/current/routing.html#route-groups-and-prefixes
symfony6-adminlte:
  type: annotation
  # the controller value has the format 'controller_class::method_name'
  resource: '../../src/Controller'
  name_prefix: 'symfony6-adminlte.'


